version: '3.9'

services:
  app:
    image: note-api:latest
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy # this service will wait till db container is healthy
    networks:
      - note-app

  db:
    image: docker.arvancloud.ir/mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306" #to check data with phpmyadmin on another container
    volumes:
      - note_mysql_data:/var/lib/mysql
    networks:
      - note-app
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  note_mysql_data:
    external: true

networks:
  note-app:
    external: true
